/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/oauth2/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取 OAuth2 重定向 URL
         * @description F-C 调用此接口获取 OAuth2 前端（F-O）的重定向地址
         */
        get: operations["getOAuth2RedirectUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OAuth2 令牌交换
         * @description Authorization Code → access_token + refresh_token
         */
        post: operations["oauth2TokenExchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth2/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OAuth2 令牌刷新
         * @description 使用 refresh_token 换取新的 access_token
         */
        post: operations["oauth2TokenRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description OAuth2 授权重定向信息 */
        OAuth2AuthorizeResponse: {
            /** @description OAuth2 Provider 授权页面的完整 URL */
            redirect_url: string;
            /** @description CSRF 防护随机状态参数，回调时需原样传回 */
            state: string;
        };
        /** @description OAuth2 通用错误响应 */
        OAuth2Error: {
            /**
             * @description 错误码：
             *     - `invalid_request`: 请求参数无效
             *     - `invalid_client`: 客户端认证失败
             *     - `invalid_grant`: 授权码无效或已过期
             *     - `server_error`: 服务器内部错误
             */
            error: string;
            /** @description 人类可读的错误描述，用于调试 */
            error_description?: string;
        };
        /** @description OAuth2 授权码交换请求，使用 Authorization Code 换取 access_token */
        OAuth2TokenExchangeRequest: {
            /** @description OAuth2 授权码，由授权回调 URL 的 query 参数携带 */
            code: string;
            /** @description 必须与授权请求中的 redirect_uri 完全一致 */
            redirect_uri: string;
            /** @description CSRF 防护 state，必须与授权请求中的 state 一致且仅使用一次 */
            state: string;
            /** @description 前端生成的设备 UUID，用于标识客户端设备 */
            device_id: string;
            /** @description 设备显示名称，如 "Chrome on Mac" */
            device_name?: string;
            /** @description 客户端 User-Agent 字符串，用于设备识别 */
            user_agent?: string;
        };
        /** @description OAuth2 令牌交换成功响应 */
        OAuth2TokenExchangeResponse: {
            /** @description JWT access token，有效期由 expires_in 指定 */
            access_token: string;
            /** @description refresh token，用于在 access_token 过期后换取新 token */
            refresh_token: string;
            /**
             * Format: int64
             * @description access token 过期时间（秒），通常为 900（15 分钟）
             */
            expires_in: number;
            /** @description 已认证用户的唯一 ID */
            user_id: string;
        };
        /** @description OAuth2 令牌刷新请求，使用 refresh_token 换取新的 access_token */
        OAuth2TokenRefreshRequest: {
            /** @description refresh token，使用一次后即失效（rotation） */
            refresh_token: string;
        };
        /** @description OAuth2 令牌刷新成功响应 */
        OAuth2TokenRefreshResponse: {
            /** @description 新的 JWT access token */
            access_token: string;
            /**
             * Format: int64
             * @description 新 access token 过期时间（秒）
             */
            expires_in: number;
        };
        /** @description protocol 内 UUID 类型，JSON 线上为字符串 */
        UUID: string;
        /** @enum {string} */
        SessionStatus: "active" | "closed" | "idle";
        /** @enum {string} */
        TurnStatus: "pending" | "running" | "completed" | "failed" | "cancelled" | "interrupted" | "merged";
        /** @enum {string} */
        MessageRole: "user" | "assistant" | "tool" | "system";
        /** @enum {string} */
        MessageStreamingStatus: "pending" | "streaming" | "completed" | "failed";
        /** @enum {string} */
        ContentType: "markdown" | "summary" | "text" | "thinking" | "toolcall_input" | "toolcall_output";
        /** @enum {string} */
        RtcStatus: "pending" | "sent" | "executing" | "completed" | "failed" | "timeout" | "rejected";
        Session: {
            id: components["schemas"]["UUID"];
            /** @description 客户端生成的幂等 ID */
            client_id?: string;
            /** @description 所有者类型（user / system） */
            owner_kind: string;
            /** @description 所有者引用 ID（user → user UUID，system → "system"） */
            owner_ref_id: string;
            /** @description 会话标题 */
            title?: string;
            status: components["schemas"]["SessionStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: date-time
             * @description 关闭时间
             */
            closed_at?: string;
            /**
             * Format: date-time
             * @description 软删除时间
             */
            deleted_at?: string;
        };
        Turn: {
            id: components["schemas"]["UUID"];
            /** @description 客户端生成的幂等 ID */
            client_id?: string;
            session_id: components["schemas"]["UUID"];
            status: components["schemas"]["TurnStatus"];
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description 开始执行时间
             */
            started_at?: string;
            /**
             * Format: date-time
             * @description 完成时间
             */
            completed_at?: string;
            /** @description 错误信息（失败时） */
            error_message?: string;
            /**
             * Format: date-time
             * @description 软删除时间
             */
            deleted_at?: string;
        };
        Message: {
            id: components["schemas"]["UUID"];
            /** @description 客户端生成的幂等 ID */
            client_id?: string;
            session_id: components["schemas"]["UUID"];
            /** @description 关联的 Turn ID */
            turn_id?: components["schemas"]["UUID"];
            /** @description 关联的父消息 ID（toolcall_output 指向 toolcall_input） */
            parent_message_id?: components["schemas"]["UUID"];
            /**
             * Format: uint32
             * @description Session 内全局顺序
             */
            global_offset: number;
            /**
             * Format: uint32
             * @description Turn 内顺序
             */
            turn_offset?: number;
            role: components["schemas"]["MessageRole"];
            /** @description 消息内容 */
            content?: string;
            streaming_status: components["schemas"]["MessageStreamingStatus"];
            /** @description 创建者类型（user / system） */
            creator_kind: string;
            /** @description 创建者引用 ID */
            creator_ref_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: date-time
             * @description 软删除时间
             */
            deleted_at?: string;
            /** @description 输入 token 数（仅 assistant 消息） */
            input_tokens?: number;
            /** @description 输出 token 数（仅 assistant 消息） */
            output_tokens?: number;
            /** @description 总 token 数（仅 assistant 消息） */
            total_tokens?: number;
            /** @description 缓存命中 token 数 */
            cached_tokens?: number;
            /** @description 推理 token 数 */
            reasoning_tokens?: number;
        };
        /**
         * @description 消息内容数据，Type 标识 Data 的具体结构，前端根据 Type 决定如何渲染。
         *     - `markdown`: Data 为字符串
         *     - `summary`: Data 为 SummaryItem[]
         *     - `text`: Data 为字符串
         *     - `thinking`: Data 为字符串
         *     - `toolcall_input`: Data 为 ToolCall 对象
         *     - `toolcall_output`: Data 为 ToolCall 对象
         */
        ContentData: {
            type: components["schemas"]["ContentType"];
            /** @description 具体内容（结构由 type 决定），类型取决于 type 字段 */
            data: unknown;
        };
        ToolCall: {
            id: components["schemas"]["UUID"];
            tool_name: string;
            input: string;
            output?: string;
            status?: string;
        };
        /** @description 远程 Tool 调用模型 */
        Rtc: {
            id: components["schemas"]["UUID"];
            /** @description 客户端生成的幂等 ID */
            client_id?: string;
            session_id: components["schemas"]["UUID"];
            turn_id: components["schemas"]["UUID"];
            /** @description 关联的 toolcall_input Message 记录 ID */
            message_id?: components["schemas"]["UUID"];
            /** @description 关联的 toolcall_output Message 记录 ID */
            output_message_id?: components["schemas"]["UUID"];
            /**
             * Format: uint32
             * @description Turn 内的顺序
             */
            offset: number;
            /** @description Tool 名称 */
            tool_name: string;
            /** @description Tool 参数（JSON Schema） */
            parameters?: unknown;
            status: components["schemas"]["RtcStatus"];
            /** @description 执行结果 */
            result?: unknown;
            /** @description 错误信息（失败时） */
            error_message?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: date-time
             * @description 完成时间
             */
            completed_at?: string;
            /**
             * Format: date-time
             * @description 软删除时间
             */
            deleted_at?: string;
        };
        /** @enum {string} */
        UpdateEntity: "session" | "turn" | "message" | "rtc";
        /** @enum {string} */
        UpdateAction: "created" | "updated" | "deleted";
        /** @enum {string} */
        UpdateType: "gap";
        /** @description 单条实体变化记录 */
        UpdateItem: {
            entity: components["schemas"]["UpdateEntity"];
            action: components["schemas"]["UpdateAction"];
            entity_id: components["schemas"]["UUID"];
        };
        /** @description 实体变化事件，随操作类 RPC 响应下发，前端收到后更新本地状态保持实时同步 */
        Update: {
            id: components["schemas"]["UUID"];
            /** @description 变化条目列表 */
            items: components["schemas"]["UpdateItem"][];
            /** @description 实体数据（可选，与 items 一一对应） */
            data_list?: unknown[];
            /**
             * Format: uint32
             * @description 用户维度单调递增 offset
             */
            offset: number;
        };
        /** @description gap 占位数据，客户端收到后只推进 offset，不做业务处理 */
        UpdateDataGap: Record<string, never>;
        CloseSessionRequest: {
            session_id: components["schemas"]["UUID"];
            /** @description 客户端生成的幂等 ID */
            client_id?: string;
        };
        CloseSessionResult: {
            success: boolean;
        };
        /** @description 关闭会话响应 */
        CloseSessionResponse: {
            result: components["schemas"]["CloseSessionResult"];
            updates?: components["schemas"]["Update"][];
        };
        /** @description 更新会话请求（目前仅支持标题） */
        UpdateSessionRequest: {
            session_id: components["schemas"]["UUID"];
            /** @description 新标题（不传表示不修改） */
            title?: string;
        };
        UpdateSessionResult: {
            session_id: components["schemas"]["UUID"];
        };
        /** @description 更新会话响应 */
        UpdateSessionResponse: {
            result: components["schemas"]["UpdateSessionResult"];
            updates?: components["schemas"]["Update"][];
        };
        /** @description 发送消息请求，自动创建 session（如不存在）和 turn */
        SendMessageRequest: {
            /** @description 可选，为空时自动创建 session */
            server_session_id?: components["schemas"]["UUID"];
            /** @description 必填 */
            client_session_id: string;
            content_data: components["schemas"]["ContentData"];
            /** @description 客户端生成的幂等 ID */
            client_id: string;
        };
        SendMessageResult: {
            session_id: components["schemas"]["UUID"];
            turn_id: components["schemas"]["UUID"];
            message_id: components["schemas"]["UUID"];
        };
        /** @description 发送消息响应 */
        SendMessageResponse: {
            result: components["schemas"]["SendMessageResult"];
            updates?: components["schemas"]["Update"][];
        };
        /** @description 分叉对话 */
        ForkSessionRequest: {
            content_data: components["schemas"]["ContentData"];
            /** @description 客户端生成的幂等 ID */
            new_client_message_id: string;
            /** @description 旧 session ID */
            old_server_session_id: components["schemas"]["UUID"];
            /** @description 新 session ID */
            new_client_session_id: components["schemas"]["UUID"];
            /** @description Fork 多少条消息？默认200；最多1000条； */
            limit?: number;
            /** @description 旧 message ID */
            old_server_message_id: components["schemas"]["UUID"];
        };
        ForkSessionResult: {
            session_id: components["schemas"]["UUID"];
            turn_id: components["schemas"]["UUID"];
            message_ids: components["schemas"]["UUID"][];
        };
        /** @description Fork对话响应 */
        ForkSessionResponse: {
            result: components["schemas"]["ForkSessionResult"];
            updates?: components["schemas"]["Update"][];
        };
        StopTurnRequest: {
            session_id: components["schemas"]["UUID"];
            /** @description 客户端生成的幂等 ID */
            client_id?: string;
        };
        StopTurnResult: {
            success: boolean;
        };
        /** @description 停止 Turn 响应 */
        StopTurnResponse: {
            result: components["schemas"]["StopTurnResult"];
            updates?: components["schemas"]["Update"][];
        };
        UpdateRtcStatusRequest: {
            rtc_id: components["schemas"]["UUID"];
            status: components["schemas"]["RtcStatus"];
            /** @description 客户端生成的幂等 ID */
            client_id?: string;
        };
        UpdateRtcStatusResult: {
            success: boolean;
        };
        /** @description 更新 RTC 状态响应 */
        UpdateRtcStatusResponse: {
            result: components["schemas"]["UpdateRtcStatusResult"];
            updates?: components["schemas"]["Update"][];
        };
        /** @description 提交 RTC 执行结果请求 */
        SubmitRtcResultRequest: {
            rtc_id: components["schemas"]["UUID"];
            /** @description 是否执行成功 */
            success: boolean;
            /** @description 执行结果（成功时） */
            result?: unknown;
            /** @description 错误信息（失败时） */
            error?: string;
            /** @description 客户端生成的幂等 ID */
            client_id?: string;
        };
        SubmitRtcResultResult: {
            success: boolean;
        };
        /** @description 提交 RTC 执行结果响应 */
        SubmitRtcResultResponse: {
            result: components["schemas"]["SubmitRtcResultResult"];
            updates?: components["schemas"]["Update"][];
        };
        /**
         * @description RPC 方法名，前后端统一从 protocol 导入，禁止硬编码字符串
         * @enum {string}
         */
        RpcMethod: "v1.session.list" | "v1.session.get" | "v1.session.close" | "v1.session.update" | "v1.session.fork" | "v1.message.send" | "v1.message.list" | "v1.message.get" | "v1.turn.list" | "v1.turn.get" | "v1.turn.stop" | "v1.rtc.list" | "v1.rtc.get" | "v1.rtc.update_status" | "v1.rtc.submit_result";
        /** @description 获取会话列表请求 */
        ListSessionsRequest: {
            /** @description 分页游标（上一页最后一条的 ID） */
            cursor?: string;
            /** @description 每页数量，默认 20 */
            limit?: number;
        };
        ListSessionsResponse: {
            items: components["schemas"]["Session"][];
            /** @description 下一页游标，为空表示没有更多数据 */
            next_cursor?: string;
        };
        GetSessionRequest: {
            session_id: components["schemas"]["UUID"];
        };
        GetSessionResponse: {
            item: components["schemas"]["Session"];
        };
        /** @description 获取消息列表请求 */
        MessageListRequest: {
            session_id: components["schemas"]["UUID"];
            /**
             * Format: uint32
             * @description 分页游标（上一页最后一条的 global_offset）
             */
            cursor?: number;
            /** @description 每页数量，默认 50 */
            limit?: number;
        };
        MessageListResponse: {
            items: components["schemas"]["Message"][];
            /**
             * Format: uint32
             * @description 下一页游标
             */
            next_cursor?: number;
        };
        MessageGetRequest: {
            message_id: components["schemas"]["UUID"];
        };
        MessageGetResponse: {
            item: components["schemas"]["Message"];
        };
        /** @description 获取 RTC 列表请求 */
        RtcListRequest: {
            session_id: components["schemas"]["UUID"];
            /** @description 分页游标（上一页最后一条的 ID） */
            cursor?: string;
            /** @description 每页数量，默认 50 */
            limit?: number;
        };
        RtcListResponse: {
            items: components["schemas"]["Rtc"][];
            /** @description 下一页游标 */
            next_cursor?: string;
        };
        RtcGetRequest: {
            rtc_id: components["schemas"]["UUID"];
        };
        RtcGetResponse: {
            item: components["schemas"]["Rtc"];
        };
        /** @description 获取 Turn 列表请求 */
        TurnListRequest: {
            session_id: components["schemas"]["UUID"];
            /** @description 分页游标（上一页最后一条的 ID） */
            cursor?: string;
            /** @description 每页数量，默认 50 */
            limit?: number;
        };
        TurnListResponse: {
            items: components["schemas"]["Turn"][];
            /** @description 下一页游标 */
            next_cursor?: string;
        };
        TurnGetRequest: {
            turn_id: components["schemas"]["UUID"];
        };
        TurnGetResponse: {
            item: components["schemas"]["Turn"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOAuth2RedirectUrl: {
        parameters: {
            query: {
                /** @description OAuth2 Provider 名称（如 "github"） */
                provider: string;
                /** @description 客户端回调地址（Provider 授权完成后重定向到此地址） */
                redirect_uri: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuth2AuthorizeResponse"];
                };
            };
        };
    };
    oauth2TokenExchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuth2TokenExchangeRequest"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuth2TokenExchangeResponse"];
                };
            };
        };
    };
    oauth2TokenRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuth2TokenRefreshRequest"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuth2TokenRefreshResponse"];
                };
            };
        };
    };
}
